/**
 * Cross-references the TCMAP sites against agencies participating in
 * Minnesota's Homeless Management Information System.
 *
 *   node scripts/match-hmis.mjs
 *
 * Writes src/data/hmis-matches.json, which convert-tcmap.mjs then layers onto
 * the directory. The output is committed so the matches can be reviewed and
 * corrected by hand — this is fuzzy name matching, and it should be read
 * before it is trusted.
 *
 * WHY IT MATTERS: HMIS agencies are the ones that do intakes with people
 * experiencing homelessness. An agency in this list is plugged into
 * coordinated entry and can start a housing referral. That is a different and
 * scarcer thing than a hot meal.
 *
 * THE CAVEAT THAT SHAPES EVERYTHING BELOW: HMIS participation is recorded at
 * the AGENCY level, and the directory is a list of SITES. "VEAP" participates
 * in HMIS; that does not mean VEAP's mobile food pantry at a mosque parking
 * lot can do a housing intake. So the tag claims only what the data supports —
 * that the site is run by an HMIS agency — and every card names the agency it
 * matched so a reader can judge for themselves.
 *
 * The matcher is tuned for precision over recall. A missed match costs a
 * filter hit; a false one tells someone sleeping outside that a food shelf can
 * start their housing paperwork.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const HMIS = resolve(root, "src/data/Agencies Participating In MN's HMIS-Grid view.csv");
const ANCHORS = resolve(root, 'src/data/anchors.json');
const OUT = resolve(root, 'src/data/hmis-matches.json');

function parseCsv(text) {
  const rows = [];
  let field = '', row = [], quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else quoted = false; }
      else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const norm = (s) => s.toLowerCase()
  .replace(/[’']/g, '')
  .replace(/\b(inc|llc|incorporated|corp|co)\b/g, ' ')
  .replace(/[^a-z0-9]+/g, ' ')
  .replace(/\s+/g, ' ')
  .trim();

/**
 * A real acronym: mostly capitals, 3-6 characters, no spaces. "SACA", "IOCP",
 * and "VEAP" qualify. Plenty of this file's "abbreviations" are just short
 * names — "Agate", "Bridge", "Hennepin" — and matching on those produced
 * false positives like Hennepin Technical College <- Hennepin County.
 */
function isAcronym(abbr) {
  if (!abbr || abbr.length < 3 || abbr.length > 6 || /\s/.test(abbr)) return false;
  const letters = abbr.replace(/[^A-Za-z]/g, '');
  const caps = letters.replace(/[^A-Z]/g, '').length;
  return letters.length >= 3 && caps >= 3 && caps >= letters.length - 1;
}

/**
 * Guards the reversed rule (site name inside agency name). Without it,
 * "Task Force, Inc." matches "Indigenous Peoples Task Force" — two unrelated
 * organizations sharing a generic phrase.
 */
const hasDistinctiveWord = (s) =>
  norm(s).split(' ').some((t) => t.length >= 6 && !GENERIC.has(t));

const GENERIC = new Set([
  'community', 'center', 'centre', 'church', 'services', 'service', 'program',
  'programs', 'project', 'ministries', 'ministry', 'county', 'housing',
  'shelter', 'outreach', 'resource', 'resources', 'family', 'families',
]);

function match(agency, anchor) {
  const a = norm(agency.name);
  const n = norm(anchor.name);
  if (!a || !n) return null;

  if (a.split(' ').length >= 2 && ` ${n} `.includes(` ${a} `)) return 'full name';

  if (n.split(' ').length >= 2 && ` ${a} `.includes(` ${n} `) && hasDistinctiveWord(n)) {
    return 'site name inside agency name';
  }

  if (isAcronym(agency.abbr)) {
    const abbr = norm(agency.abbr);
    if (abbr && ` ${n} `.includes(` ${abbr} `)) return `acronym ${agency.abbr}`;
  }
  return null;
}

// ---------------------------------------------------------------------------

const rows = parseCsv(readFileSync(HMIS, 'utf8').replace(/^﻿/, ''));
const agencies = rows.slice(1)
  .filter((r) => r[0]?.trim())
  .map((r) => ({ name: r[0].trim(), abbr: (r[1] || '').trim() }));

const anchors = JSON.parse(readFileSync(ANCHORS, 'utf8'));

const matches = {};
for (const anchor of anchors) {
  for (const agency of agencies) {
    const why = match(agency, anchor);
    if (!why || matches[anchor.id]) continue;
    matches[anchor.id] = { site: anchor.name, agency: agency.name, matchedBy: why };
  }
}

const payload = {
  _comment:
    "Generated by scripts/match-hmis.mjs from \"Agencies Participating In MN's HMIS-Grid view.csv\". " +
    'Consumed by scripts/convert-tcmap.mjs. HMIS participation is recorded per AGENCY, not per site: ' +
    'a match means this site is run by an agency that does homeless intakes somewhere, not that intakes ' +
    'happen at this address. Reviewed by hand — delete an entry to reject a bad match.',
  _generated: '2026-07-29',
  matches,
};

writeFileSync(OUT, JSON.stringify(payload, null, 2) + '\n');

const agencyCount = new Set(Object.values(matches).map((m) => m.agency)).size;
console.log(`agencies in HMIS list : ${agencies.length}`);
console.log(`sites in directory    : ${anchors.length}`);
console.log(`sites matched         : ${Object.keys(matches).length}  (${agencyCount} distinct agencies)`);
console.log(`\nwrote ${OUT.replace(root + '/', '')}`);
for (const [id, m] of Object.entries(matches)) {
  console.log(`  ${m.site}\n      <- ${m.agency}  [${m.matchedBy}]`);
}
